---

- name: setup | ensure deploy root directory exists
  sudo: True
  file: path={{ app_deploy_dir }} owner={{ remote_user }}

- name: setup | ensure nginx config for app exists
  sudo: True
  template: src=nginx_vhost_config.j2 dest=/etc/nginx/sites-available/{{ app_name }}.conf
  register: app_nginx_config
  when: app_host is defined

- name: setup | ensure nginx is reloaded after nginx config for app has changed
  sudo: True
  service: name=nginx state=reloaded
  when: app_nginx_config is defined and app_nginx_config.changed

- name: setup | ensure unzip is installed
  sudo: True
  apt: update_cache=yes name=unzip state=latest

