---

- apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
  - "python"
  - "python-pip"
  sudo: True

- pip:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ python_modules }}"
  sudo: True
