---

- name: undeploy | ensure nginx config for app is disabled
  sudo: True
  file: path=/etc/nginx/apps-enabled/{{ app_name }}.conf state=absent
  when: app_host is defined

- name: undeploy | ensure nginx config for app is removed
  sudo: True
  file: path=/etc/nginx/apps-available/{{ app_name }}.conf state=absent
  when: app_host is defined

- name: deploy | ensure nginx is reloaded after disabling and removing nginx config for app
  sudo: True
  service: name=nginx state=reloaded
  when: app_host is defined

- name: undeploy | ensure app root directory is removed
  sudo: True
  file: path=/mnt/deploy/{{ app_name }} state=absent

