app_deploy_path: "/mnt/deploy/{{ app_name }}"
app_archive_path: "{{ app_deploy_path }}/artefacts"
app_release_path: "{{ app_deploy_path }}/releases/{{ app_version }}"
app_symlink_deeplink_dir: ""
app_environment: {}
