---
- name: deploy app {{ app_name }}
  hosts: tag_Apps_symanex-site:tag_Apps_*,symanex-site:tag_Apps_symanex-site,*
  remote_user: "{{ remote_user }}"
  roles:
  - { role: app_deploy }
  vars:
  - app_name: "symanex-site"
  - app_repo: "symanex/symanex-site"
  - app_version: "master"
  - app_host: "www.symanex.com"
