---

- apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  sudo: True

- apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  sudo: True

- apt: name=jenkins state=latest update_cache=yes
  sudo: True

- lineinfile: dest=/etc/default/jenkins regexp=^HTTP_PORT= line=HTTP_PORT={{ jenkins_port }}
  sudo: True
  register: jenkins_port_config

- template: src=config.xml.j2 dest=/var/lib/jenkins/config.xml owner=jenkins group=jenkins
  sudo: True
  register: jenkins_main_config

- user: name=jenkins groups=shadow shell=/sbin/nologin append=yes
  sudo: True
  register: jenkins_user

- file: path="{{ jenkins_user.home }}/.ssh" owner="jenkins" group="jenkins" state="directory"
  sudo: True

- copy: src="jenkins_user_id_rsa" dest="{{ jenkins_user.home }}/.ssh/id_rsa" owner="jenkins" group="jenkins" mode=0400
  sudo: True

- file: path="{{ jenkins_user.home }}/users/jenkins" owner="jenkins" group="jenkins" state="directory" recurse=yes
  sudo: True

- template: src="user.xml.j2" dest="{{ jenkins_user.home }}/users/jenkins/config.xml" owner="jenkins" group="jenkins"
  sudo: True
  register: jenkins_user_public_key

- service: name=jenkins state=restarted
  sudo: True
  when: jenkins_port_config.changed or jenkins_main_config.changed or jenkins_user_public_key.changed

- user: name="{{ item.key }}" group="{{ jenkins_users_group }}" groups="{{ jenkins_admin_group }}" password="{{ item.value }}" append=yes
  sudo: True
  with_dict: "{{ jenkins_admin_users }}"
  when: jenkins_admin_users is defined

- service: name=jenkins state=started
  sudo: True

- wait_for: port="{{ jenkins_port }}"

# requires httplib2
- uri: url="http://localhost:{{ jenkins_port }}" status_code=200,403,503 timeout=300
  register: jenkins_wait
  until: jenkins_wait.status == 200 or jenkins_wait.status == 403
  retries: 60

- get_url: url="http://jenkins:@localhost:{{ jenkins_port }}/jnlpJars/jenkins-cli.jar" dest="{{ jenkins_user.home }}/jenkins-cli.jar" owner="jenkins" group="jenkins"
  sudo: True
  register: jenkins_cli_download

- name: get list of installed plugins
  shell: "java -jar {{ jenkins_user.home }}/jenkins-cli.jar -s http://localhost:{{ jenkins_port }}/ list-plugins | awk '{print $1}'"
  sudo: True
  sudo_user: jenkins
  register: jenkins_plugins_present
  changed_when: False

- name: install and update plugins
  shell: "java -jar {{ jenkins_user.home }}/jenkins-cli.jar -s http://localhost:{{ jenkins_port }} install-plugin {{ item }}"
  sudo: True
  sudo_user: jenkins
  with_items: "{{ jenkins_plugins | difference(jenkins_plugins_present.stdout_lines) }}"
  register: jenkins_plugin_installation

- service: name=jenkins state=restarted
  sudo: True
  when: jenkins_plugin_installation | changed

- service: name=jenkins state=started
  sudo: True
